module.exports = {
  development: {
    type: 'sqlite',
    database: `${__dirname}/database.sqlite`,
    synchronize: true,
    logger: 'debug',
    logging: true,
    entities: [`${__dirname}/server/entity/**/*.js`],
    migrations: ['server/migration/*.js'],
    subscribers: ['server/subscriber/*.js'],
    cli: {
      entitiesDir: 'server/entity',
      migrationsDir: 'server/migration',
      subscribersDir: 'server/subscriber',
    },
  },
  test: {
    type: 'sqlite',
    database: ':memory:',
    synchronize: true,
    logger: 'debug',
    logging: true,
    entities: [`${__dirname}/server/entity/**/*.js`],
    migrations: ['server/migration/*.js'],
    subscribers: ['server/subscriber/*.js'],
    cli: {
      entitiesDir: 'server/entity',
      migrationsDir: 'server/migration',
      subscribersDir: 'server/subscriber',
    },
  },
  production: {
    type: 'postgres',
    synchronize: true,
    logger: 'debug',
    logging: true,
    url: process.env.DATABASE_URL,
    entities: ['dist/entity/**/*.js'],
    migrations: ['dist/migration/*.js'],
    subscribers: ['dist/subscriber/*.js'],
    cli: {
      entitiesDir: 'dist/entity',
      migrationsDir: 'dist/migration',
      subscribersDir: 'dist/subscriber',
    },
  },
};
