module.exports = [
  {
    name: 'development',
    type: 'sqlite',
    database: `${__dirname}/database.sqlite`,
    synchronize: false,
    migrationsRun: true,
    logger: 'advanced-console',
    logging: ['query'],
    entities: [`${__dirname}/server/entity/**/*.js`],
    migrations: ['server/migrations/*.js'],
    subscribers: ['server/subscriber/*.js'],
    cli: {
      entitiesDir: 'server/entity',
      migrationsDir: 'server/migrations',
      subscribersDir: 'server/subscriber',
    },
  },
  {
    name: 'test',
    type: 'sqlite',
    database: ':memory:',
    synchronize: true,
    logger: 'debug',
    logging: true,
    entities: [`${__dirname}/server/entity/**/*.js`],
    migrations: ['server/migrations/*.js'],
    subscribers: ['server/subscriber/*.js'],
    cli: {
      entitiesDir: 'server/entity',
      migrationsDir: 'server/migrations',
      subscribersDir: 'server/subscriber',
    },
  },
  {
    name: 'production',
    type: 'postgres',
    synchronize: false,
    migrationsRun: true,
    logger: 'debug',
    logging: true,
    url: process.env.DATABASE_URL,
    entities: ['dist/entity/**/*.js'],
    migrations: ['dist/migrations/*.js'],
    subscribers: ['dist/subscriber/*.js'],
    cli: {
      entitiesDir: 'dist/entity',
      migrationsDir: 'dist/migrations',
      subscribersDir: 'dist/subscriber',
    },
  },
];
